site:
  title: Naresh Chaurasia
  start_page: my-component::index.adoc

content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: build/site

runtime:
  cache_dir: .antora/cache

asciidoc:
  attributes:
    icons: font
    sectnums!:
    toc: right
    toclevels: 5

    source-highlighter: highlight.js
    highlightjs-theme: github

  extensions:
    - ./extensions/reel-extension.js

antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true

    # ✅ ADD THIS
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options:
        start_on_load: true