site:
  title: Antora Site
  start_page: my-component::index.adoc

content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: build/site

runtime:
  cache_dir: .antora/cache

asciidoc:
  attributes:
    icons: font
    sectnums: ''
    toc: left