= The Compound Effect
:toc: right
:toclevels: 5
:sectnums:
:sectnumlevels: 5

== Introduction

* We’ve lost sight of the simple but profound fundamentals of what it takes to be successful.
* You do not need new information — *you need a new plan of action* . It is time to create new behaviors and habits oriented away from sabotage and toward success . It’s that simple.



== Chapter 1: The Compound Effect In Action

* It doesn’t matter how smart you are or aren’t , _you need to *make up in hard work* what you lack in experience , skill , intelligence , or innate ability_ . If your competitor is smarter , more talented , or experienced , you simply need to work three or four times as hard.
* If you aren’t good at something, work harder, work smarter. He walked his talk, too.

== Chapter 2: Choices

* It’s the little things in life that will bite you .

* I have not been any more lucky or unlucky than anyone else . *The difference is when luck came my way, I took advantage of it*.

* The ( Complete ) Formula for Getting Lucky : Preparation (personal growth) + Attitude (belief / mindset) + Opportunity (a good thing coming your way) + Action (doing something about it) = Luck

* Attitude : This is where luck evades most people , and where Sir Richard is spot - on with his belief that luck is all around us. It’s simply a matter of seeing situations , conversations, and circumstances as fortuitous . *You cannot see what you don’t look for, and you cannot look for what you don’t believe in*.

* So no more whining about the cards you were dealt, the great defeats you suffered, or any other circumstances. *Countless people have more disadvantages and greater obstacles than you , and yet they’re wealthier and more fulfilled*.Luck is an equal - opportunity distributor . Lady luck shines on all , but rather than having your umbrella overhead , you’ve got to have your face to the sky When it comes down to it, it’s all you, baby. There’s no other way around it.

---

* *When I learned of the wrongdoings, I chose not to lose any more time fighting it. Instead, I licked my wounds, learned my lesson, and moved on*.. In hindsight, I’d make the same choice to pick up and move on again today.

[quote]
*I have done mistake. Lost time, money and peace of mind. Loss of self-respect, fear of LG. She is fucked up and shameless liar. Accept your defeat and Move on. This is deadend. Look for meaningful relationship*.
*Date*: 2025-10-25
*Category*: Relationship
*Tags*: Girl, Ashtray

---

* I now challenge you to do the same. *No matter what has happened to you, take complete responsibility for it — good or bad, victory or defeat*. Own it. My mentor Jim Rohn said, *"The day you graduate from childhood to adulthood is the day you take full responsibility for your life."*

---

* *This tracking exercise changed my awareness** of how I related to my money. It worked so well, in fact, that I’ve used it many times to change other behaviors. Tracking is my go - to transformation model for everything that ails me. Over the years I’ve tracked what I eat and drink, how much I exercise, how much time I spend improving a skill, my number of sales calls, even the improvement of my relationships with family, friends, or my spouse. The results have been no less profound than my money - tracking wake - up call.

[quote]
*Simple tracking to find out if 1 hour of practise session is worth 1 hour*.
*Date*: 2025-10-25
*Category*:
*Tags*:

* After hundreds of tournaments played and thousands of strokes tallied , the difference between the No . 1 – ranked golfer and the No . 10 golfer is an average of 0.32 strokes, but the difference in prize money is more than double ( $ 9.6 million versus $ 4.6 million ) ! The No. 1 golfer isn’t five times better, not even 50 percent or 10 percent better . In fact, his average score is only 0.5 percent better. Yet the results are more than double !

* *Even though you saved for many more years and invested much more cash, you still ended up with less than a third of the money you could have had. That’s what happens when we procrastinate and neglect necessary behaviors, habits, and disciplines. Don’t wait another day to start the small disciplines that will lead you in the direction of your goals!*

* *The key is to start NOW*. Every great act , every fantastic adventure , starts with small steps . The first step always looks harder than it actually is.

== Chapter 3: Habits

* "My son, you have just demonstrated the power that habits will have over your life !" the teacher exclaimed. "The older they are, the bigger they get, the deeper the roots grow, and the harder they are to uproot. Some get so big, with roots so deep, you might hesitate to even try."

* *From what we’ve already discussed , you know successful people aren’t necessarily more intelligent or more talented than anyone else. But their habits take them in the direction of becoming more informed, more knowledgeable, more competent, better skilled, and better prepared.*

* Like Larry Bird, you can condition your automatic and unconscious responses to be those of a developed champion . This chapter is about *choosing to make up for what you lack in innate ability with discipline, hard work, and good habits*. It’s about becoming a creature of champion habits .

* *Forget about willpower. It’s time for why - power. Your choices are only meaningful when you connect them to your desires and dreams. The wisest and most motivating choices are the ones aligned with that which you identify as your purpose, your core self, and your highest values. You’ve got to want something, and know why you want it , or you’ll end up giving up too easily.*


* Well said. That’s why it’s not enough to choose to be successful. You have to dig deeper than that to find your core motivation, to activate your superpower. Your why - power .

* We can all make powerful choices . We can all take back control by not blaming chance, fate, or anyone else for our outcomes. It’s within our ability to create change. *Rather than letting past hurtful experiences sap our energy and sabotage our success, we can use them to fuel positive, constructive change*.

* When you define your goals , you give your brain something new to look for and focus on. It’s as if you’re giving your mind a new set of eyes through which to see all the people , circumstances, conversations, resources, ideas, and creativity surrounding you. With this new perspective(an inner itinerary), your mind proceeds to match up on the outside what you want most on the inside — your goal. It’s that simple. The difference in how you experience the world and draw ideas, people, and opportunities into your life after you have clearly defined your goals is profound. In one of my interviews with Brian Tracy, he put it this way :**"Top people have very clear goals. They know who they are and they know what they want. They write it down and they make plans for its accomplishment. Unsuccessful people carry their goals around in their head like marbles rattling around in a can, and we say a goal that is not in writing is merely a fantasy. And everybody has fantasies, but those fantasies are like bullets with no powder in the cartridge. People go through life shooting blanks without written goals — and that’s the starting point."**

* I suggest that you take some time today to make a list of your most important goals. I recommend considering goals in all aspects of your life, not just for your business or finances. Be wary of the high price of putting too much focus on any single aspect of your life, to the exclusion of everything else. Go for whole - life success — balance in all the aspects of life that are important to you: business, finances, health and well - being, spirituality, family and relationships, and lifestyle.

* When most people set out to achieve new goals, they ask, “Okay , I have my goal; now what do I need to do to get it? ” It’s not a bad question, but it’s not the first question that needs to be addressed either. The question we should be asking ourselves is : *“Who do I need to become?”* You probably know some people who seem to do everything right, but still don’t produce the results they want, right? Why not ? One principle Jim Rohn taught me is : "If you want to have more, you have to become more. Success is not something you pursue. What you pursue will elude you; it can be like trying to chase butterflies. *Success is something you attract by the person you become*."

== Chapter 4: Momentum

* *But you set yourself up for failure by doing too much too soon.*

== Chapter 5: Influences

* As you might guess, I don’t watch or listen to any news and I don’t read any news feeds or news publications. Ninety - nine percent of all news has no bearing on my personal life or my personal goals, dreams, and ambitions anyway. I have set up a few RSS feeds identifying the news and industry updates that do pertain to my direct interests and goals. The news that’s helpful to me gets plucked out of the fray so I don’t have to get any mud slung into my glass of water. While most people wade through hours of irrelevant garbage that hampers their thinking and crushes their spirit, *I get the most productive information I need when I need it, in less than fifteen minutes a day*.

* I once had a neighbor who was deemed a three - minute friend . For three minutes, we could have a great chit - chat, but we wouldn’t mesh for three hours. I can hang out with an old high - school friend for three hours, but he’s not a three - day guy And, then there are some people I can hang around for a few days, but wouldn’t go on an extended vacation with. *Take a look at your relationships. Make sure you’re not spending three hours with a three - minute person*.

* You have to let go of some people from you life. They just seem to be very different from the way you are. They have different dreams, different aspirations, different life journeys. Make peace with reality and enjoy your journey.

* When I push too hard I push him/her away. I am actually trying to help myself, and not the other way round.

* *You, too , can have almost any mentor you want*, if he or she has gathered their best thoughts, stories, and ideas into books, videos, and podcasts . You have an unlimited bounty from which to draw. Take advantage of it. Now people often reach out to my assistant in order to get my advice or mentorship. All she has to do is tell them it’s all already available from anywhere in the world through DarrenDaily or inside our Darren Hardy Training Vault.

* If you want to have a better, deeper, more meaningful relationship, ask yourself, *“Who has the type of relationship I want? How can I spend (more) time with that person? Who can I meet who can positively influence me?”* Let their glow rub off on you. *Befriend the person you think is the biggest, baddest, most successful person in your field. What do they read? Where do they go for lunch? How can that association influence you? You can build these expanded associations by joining networking groups and even online communities. Find the charity organizations, symphonies, and clubs where the people you want to emulate gather*.

* You’re never too good for a mentor . My friend Harvey Mackay told me , “I have had twenty coaches, if you can believe it. I have a speech coach, I have a writing coach, I have a humor coach, I’ve got a language coach, and on and on.” *I have always found it interesting that the most successful people , the truly top performers , are the ones willing to hire and pay for the best coaches and trainers there are. It pays to invest in your improved performance*.

* *Put another way, you will get in life what you accept and expect you are worthy of*

* *It’s amazing how life will organize around the standards you set for yourself*. Some people think they’re the victims of other people’s behavior, but in actuality, we have control over how people treat us. Protect your emotional, mental, and physical space. Then you can live with peace, rather than in the chaos and stress the world will hurl upon you.

== Chapter 6: Acceleration

* But instead of quitting, every time I hit one of those mental and emotional walls, I recognized my competitors were facing the same challenges. I knew this was another moment when, if I kept going, I would gain strides ahead of them. These were the defining moments of success and progress. It wasn’t difficult, painful, or challenging when I was just running with the herd, just keeping up, but not really getting ahead. *It’s not getting to the wall that counts. It’s what you do after you hit it that really matters*.


#Every time I hit one of those mental and emotional walls, I kept going. These were the defining moments of success and progress. It’s not getting to the wall that counts. It’s what you do after you hit it that really matters.#

* *It’s the extra effort after you have done your best that is the difference* - maker. His team went on to win the game in the second half. That is how you win.

* When conditions are great, things are easy, there aren’t any distractions, no one is interrupting, temptations aren’t luring, and nothing is disturbing your stride. *It’s not until situations are difficult, when problems come up and temptation is great, that you get to prove your worthiness for progress. As Jim Rohn would say , “Don’t wish it were easier; wish you were better*.”

* When you hit the wall in your disciplines, routines, rhythms, and consistency, realize that’s when you are separating yourself from your old self, scaling that wall and finding your more powerful, triumphant, and victorious self.
