= Good Vibe Good Life
:toc: right
:toclevels: 5
:sectnums: 5
:sectnumlevels: 5

include::books-header.adoc[]

---

== 📘 Introduction 

> When you start loving yourself, life starts loving you, too. By keeping your vibration high, you’ll attract more opportunities and blessings into your life.


During my late teens, I wished a lot of these memories would just go away. I wanted to erase them so that I was no longer reminded of the struggles I’d faced as a child. I was even embarrassed by some of them. I felt uncomfortable with who I was. There were times when I said and did things that didn’t match the child/person I was deep down. I often felt hurt by the world – and wanted to hurt it back.

> I realize that the good, the bad and the downright ugly events are all a part of who I’ve become. 

Although some of them may have been painful, they’re a blessing – they’ve taught me so much. My experiences have left me with a drive to find a way out of misery and a path towards a better life.

> Stop trying to impress people. Impress yourself. Stretch yourself. Test yourself. Be the best version of you that you can be.

> Dialy Goal: Be Better than who I was yesterday. 

##############################################

---

== What is self-love?

> It is important to recognize that it's not unjust to let go of those who show no concern for you.

