= Show Your Work
:toc: right
:toclevels: 5
:sectnums: 5
:sectnumlevels: 5

include::books-header.adoc[]

---

== 📘 Introduction (✔️ Kindle Export)

Almost all of the people I look up to and try to steal from today, regardless of their profession, **have built sharing into their routine**. These people aren’t schmoozing at cocktail parties; they’re too busy for that. They’re cranking away in their studios, their laboratories, or their cubicles, but instead of maintaining absolute secrecy and hoarding their work, **they’re open about what they’re working on, and they’re consistently posting bits and pieces of their work, their ideas, and what they’re learning online**.


[IMPORTANT]
====
* The quotes using **Canva @Instagram** is the simplest and surest way to let the world know what you are thinking.
====

##############################################

---

[NOTE]
====
* nc_naresh_chaurasia: Dance, Exercise, Art, Thoughts
* coding_with_naresh: Coding, AI, Tech, Thoughts
====


##############################################

---



Instead of wasting their time ‘networking,’ they’re taking advantage of the network. By generously sharing their ideas and their knowledge, they often gain an audience that they can then leverage when they need it—for fellowship, feedback, or patronage.

If **Steal Like an Artist** was a book about stealing influence from other people, this book is about how to influence others by letting them steal from you.

While also allowing for the possibility that your work might attract a group of people who share your interests.

##############################################


== 1. 🧠 You don’t have to be a genius

That creativity is always, in some sense, a collaboration, the result of a mind connected to other minds.

Because they have little to lose, **amateurs are willing to try anything and share the results. They take chances, experiment, and follow their whims**. Sometimes, in the process of doing things in an unprofessional way, they make new discoveries. ‘In the beginner’s mind, there are many possibilities,’ said Zen monk Shunryu Suzuki. ‘In the expert’s mind, there are few.’

The real gap is between doing nothing and doing something. Amateurs know that contributing something is better than contributing nothing.

They’re just regular people who get obsessed by something and spend a ton of time thinking out loud about it.

They were terrible. . . . I wanted to get up and be terrible with them. Raw enthusiasm is contagious.

The best way to get started on the path to sharing your work is to think about what you want to learn, and make a commitment to learning it in front of others. Find a scenius, pay attention to what others are sharing, and then start taking note of what they’re not sharing. Be on the lookout for voids that you can fill with your own efforts, no matter how bad they are at first. Don’t worry, for now, about how you’ll make money or a career off it. Forget about being an expert or a professional, and wear your amateurism (your heart, your love) on your sleeve. Share what you love, and the people who love the same things will find you.

The only way to find your voice is to use it. It’s hardwired, built into you. Talk about the things you love. Your voice will follow.


It sounds a little extreme, but in this day and age, if your work isn’t online, it doesn’t exist. We all have the opportunity to use our voices, to have our say, but so many of us are wasting it. If you want people to know about what you do and the things you care about, you have to share.

== 2. ⚙️ Think process, not product



== 3. 📅 Share something small every day
== 4. 🗄️ Open up your cabinet of curiosities
== 5. 📖 Tell good stories
== 6. 🎓 Teach what you know
== 7. 🚫📢 Don’t turn into human spam
== 8. 🥊 Learn to take a punch
== 9. 💰 Sell out
== 10. 🧭 Stick around





---

* “Remembering that I’ll be dead soon is the most important tool I’ve ever encountered to help me make the big choices in life. Because almost everything—all external expectations, all pride, all



